name:                icfpc2023
version:             0.1.0.0
github:              "nobsun/icfpc2023"
license:             BSD3
author:              "Team Sampou"
maintainer:          "icfpc2023@reasoning.tokyo"
copyright:           "Copyright: (c) 2023 Team Sampou"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/icfpc2023#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- time
- array
- containers
- filepath
- directory
- process
- random
- aeson

language: GHC2021

default-extensions:
- LambdaCase
- MultiWayIf
- NPlusKPatterns
- OverloadedStrings
- NoStarIsType
- TypeFamilyDependencies
- DataKinds
- PolyKinds
- UndecidableInstances

ghc-options:
- -Wall
- -Wno-unticked-promoted-constructors
- -Wno-unused-imports
- -Wno-unused-top-binds
- -Wno-orphans

library:
  source-dirs: src
  dependencies:
  - ad
  - split
  - mwc-random
  - vector
  - numeric-optimization ==0.1.1.0
  - numeric-optimization-ad ==0.1.0.1

executables:
  icfpc2023:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2023

  solve:
    main:                solve.hs
    source-dirs:         mains
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2023

  happiness:
    main:                happiness_main.hs
    source-dirs:         mains
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-qg
    - -with-rtsopts=-N4
    dependencies:
    - icfpc2023

  try-submit:
    main:                try-submit.hs
    source-dirs:         mains
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-qg
    - -with-rtsopts=-N4
    dependencies:
    - icfpc2023

  draw-problem:
    main:                draw-problem.hs
    source-dirs:         mains
    ghc-options:
    - -rtsopts
    dependencies:
    - icfpc2023
    - JuicyPixels
    - optparse-applicative
    - primitive

  eval:
    main:                eval.hs
    source-dirs:         mains
    ghc-options:
    - -rtsopts
    dependencies:
    - icfpc2023
    - optparse-applicative

  postprocess:
    main:                postprocess_main.hs
    source-dirs:         mains
    ghc-options:
    - -rtsopts
    dependencies:
    - icfpc2023
    - optparse-applicative


tests:
  icfpc2023-test:
    main:                spec.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2023
    - hspec
    - main-tester
    build-tools:
    - hspec-discover == 2.*

  icfpc2023-doctest:
    main:                doctests.hs
    other-modules:       []
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - icfpc2023
    - doctest
